### ISSUE TITLE
Unsure if this is chocolateQuest

### ISSUE THREAD

**Issue by misterfixit** [superpatosainz/chocolateQuest#1]
http://puu.sh/gb0p3/04928184e3.txt

Like I said before im unsure if this is chocolate quest causing the issue but its the only one im unsure of.

**Comment by superpatosainz** [comment]
@misterfixit this chocolate quest fork was just a quick, unofficial one to fix some things while Chocolatin was AWOL but now he's released a new, official version. You should try that one.

Anyway, I can't seem to find anything related to CQ in your crash log.
